name: trent_u_class_locator
description: Trent University Class Locator

publish_to: "none"

version: 1.0.2-charlie-rc8

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.2
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  url_launcher: ^6.1.14
  mockito: ^5.4.2
  page_transition: ^2.1.0
  permission_handler: ^11.0.0
  gallery_saver: ^2.3.2
  path_provider: ^2.1.1
  font_awesome_flutter: ^10.5.0
  carousel_slider: ^4.2.1
  universal_html: ^2.2.4
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  glob: ^2.1.2

flutter_native_splash:
  android: true

  android_gravity: center

  android_screen_orientation: portrait

  color: "#003F22"
  color_dark: "#003F22"

  fullscreen: true

  icon_background_color: "#003F22"
  icon_background_color_dark: "#003F22"

  image: assets/icons/splash_icon.png
  image_dark: assets/icons/splash_icon.png

  ios: false

  ios_content_mode: center

  web: true

  web_image_mode: center

  android_12:
    android_gravity: center

    color: "#003F22"
    color_dark: "#003F22"

    icon_background_color: "#003F22"
    icon_background_color_dark: "#003F22"

    image: assets/icons/splash_icon.png
    image_dark: assets/icons/splash_icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/720/
    - assets/images/1080/
    - assets/images/review/
    - assets/images/find/
    - assets/images/find/720/
    - assets/images/find/1080/
    - assets/images/find/small/
    - assets/images/maps/
    - assets/images/maps/small/
    - assets/images/maps/full/
    - assets/images/wallpapers/
    - assets/images/wallpapers/1080/
    - assets/images/wallpapers/1620/
    - assets/images/wallpapers/highrez/
    - assets/images/wallpapers/macretina/
    - assets/images/wallpapers/w300/
    - assets/images/wallpapers/widescreen/

    - assets/sample.txt
  
  fonts:
    - family: ZarBrush
      fonts:
        - asset: assets/fonts/ZarBrush.ttf
